exports.STATUS_TYPE ={
  ACTIVE:"ACTIVE",
  INACTIVE:"INACTIVE"
};

exports.LANG_TYPE = {
  ADMIN_CABINET:"ADMIN_CABINET",
  CLIENT_CABINET:"CLIENT_CABINET"
}

exports.IMAGE_MODEL_OBJECT = {
  name: String,
  uuid: String,
};